openapi: 3.0.3
info:
  title: LMPS-API
  description: |-
    This is a wip API for the LMPS and external ressources.
  termsOfService: https://www.mac.de/en/terms-and-conditions/
  contact:
    email: dev@mac.de
  version: 0.0.2
servers:
  - url: https://api.mac.de/api/v1
    description: Production server
  - url: https://dev.api.mac.de/api/v1
    description: Development server
  - url: http://localhost:3000/api/v1
    description: Local development server
  - url: https://lalovosnjsp001.mac-rz.net:3000/
    description: Current testing server
tags:
  - name: project
    description: Everything about projects
  - name: customer
    description: Everything about customers
  - name: event
    description: Everything about events
paths:
  /projects:
    get:
      tags:
        - project
      summary: Get all projects
      description: |-
        Returns all projects.
        This endpoint is paginated.
      operationId: getProjects
      security:
        - bearerAuth:
          - read:project
          - read:project.all
    post:
      tags:
        - project
      summary: Create a project
      description: |-
        Creates a project.
      operationId: createProject
      security:
        - bearerAuth:
          - create:project
  /projects/{id}:
    get:
      tags:
        - project
      summary: Get a project
      description: |-
        Returns a project.
      operationId: getProject
      security:
        - bearerAuth:
          - read:project
          - read:project.all
    put:
      tags:
        - project
      summary: Update a project
      description: |-
        Updates a project.
      operationId: updateProject
      security:
        - bearerAuth:
          - update:project
          - update:project.all
    delete:
      tags:
        - project
      summary: Delete a project
      description: |-
        Deletes a project.
      operationId: deleteProject
      security:
        - bearerAuth:
          - delete:project
          - delete:project.all
  /customers:
    get:
      tags:
        - customer
      summary: Get customers
      description: |-
        Returns a list of customers.
      operationId: getCustomers
      security:
        - bearerAuth:
          - read:customer
          - read:customer.all
    post:
      tags:
        - customer
      summary: Create a customer
      description: |-
        Creates a customer.
      operationId: createCustomer
      security:
        - bearerAuth:
          - create:customer
  /customers/{id}:
    get:
      tags:
        - customer
      summary: Get a customer
      description: |-
        Returns a customer.
      operationId: getCustomer
      security:
        - bearerAuth:
          - read:customer
          - read:customer.all
    put:
      tags:
        - customer
      summary: Update a customer
      description: |-
        Updates a customer.
      operationId: updateCustomer
      security:
        - bearerAuth:
          - update:customer
          - update:customer.all
    delete:
      tags:
        - customer
      summary: Delete a customer
      description: |-
        Deletes a customer.
      operationId: deleteCustomer
      security:
        - bearerAuth:
          - delete:customer
  /events:
    get:
      tags:
        - event
      summary: Get events
      description: |-
        Returns a list of events.
      operationId: getEvents
      security:
        - bearerAuth:
          - read:event
          - read:event.all
    post:
      tags:
        - event
      summary: Create an event
      description: |-
        Creates an event.
      operationId: createEvent
      security:
        - bearerAuth:
          - create:event
  /events/{id}:
    get:
      tags:
        - event
      summary: Get an event
      description: |-
        Returns an event.
      operationId: getEvent
      security:
        - bearerAuth:
          - read:event
          - read:event.all
    put:
      tags:
        - event
      summary: Update an event
      description: |-
        Updates an event.
      operationId: updateEvent
      security:
        - bearerAuth:
          - update:event
          - update:event.all
    delete:
      tags:
        - event
      summary: Delete an event
      description: |-
        Deletes an event.
      operationId: deleteEvent
      security:
        - bearerAuth:
          - delete:event
          - delete:event.all


components:
  # requestBodies:
  securitySchemes:
    bearerAuth:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://macbrandspaces-test.eu.auth0.com/oauth/token
          authorizationUrl: https://macbrandspaces-test.eu.auth0.com/authorize
          scopes:
            openid: openid - required by default
            profile: |
              returns claims that represent basic profile information, including 
              name,
              family_name,
              given_name,
              middle_name,
              nickname,
              picture, and
              updated_at.
            email: |
              Returns the email claim, which contains the user's email address, 
              and email_verified, which is a boolean indicating whether the email address was verified by the user.
            offline_access: offline_access
            "read:project": Read Project user is assigned to
            "read:project.all": Read all projects
            "create:project": Create a new project
            "update:project": Update a project the user is assigned to
            "update:project.all": Update all projects
            "delete:project": Delete a project the user is assigned to
            "delete:project.all": Delete all projects
            "read:customer": Read Customer user is assigned to
            "read:customer.all": Read all customers
            "create:customer": Create a new customer
            "update:customer": Update a customer the user is assigned to
            "update:customer.all": Update all customers
            "delete:customer": Delete a customer the user is assigned to
            "delete:customer.all": Delete all customers
            "read:event": Read Event user is assigned to
            "read:event.all": Read all events
            "create:event": Create a new event
            "update:event": Update a event the user is assigned to
            "update:event.all": Update all events
            "delete:event": Delete a event the user is assigned to
            "delete:event.all": Delete all events
